/*
 * File: UserGrid.ui.js
 * Date: Thu Apr 01 2010 05:14:55 GMT+0800 (?D1ú±ê×?ê±??)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.9.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

UserGridUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'user list',
    store: 'UserListStore',
    stripeRows: true,
    header: false,
    border: false,
    region:'center',
    closable:true,
    initComponent: function() {
    	this.viewConfig = { forceFit: true };
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    id: 'user_add',
                    text: 'add',
                    iconCls: 'user_add'
                },
                {
                    xtype: 'button',
                    id: 'user_edit',
                    text: 'edit',
                    iconCls: 'user_edit'
                },
                {
                    xtype: 'button',
                    id: 'user_delete',
                    text: 'delete',
                    iconCls: 'user_delete'
                }
            ]
        };
        this.columns = [
        	new Ext.grid.CheckboxSelectionModel(),
            {
                xtype: 'gridcolumn',
                header: 'name',
                sortable: true,
                resizable: true,
                width: 100,
                dataIndex: 'name'
            },
            {
                xtype: 'gridcolumn',
                header: 'loginName',
                sortable: true,
                resizable: true,
                width: 100,
                dataIndex: 'loginName'
            },
            {
                xtype: 'gridcolumn',
                header: 'email',
                sortable: true,
                resizable: true,
                width: 100,
                dataIndex: 'email'
            },
            {
                xtype: 'gridcolumn',
                header: 'region',
                sortable: true,
                resizable: true,
                width: 100,
                dataIndex: 'regionName'
            },
            {
                xtype: 'gridcolumn',
                header: 'role',
                sortable: true,
                resizable: true,
                width: 100,
                dataIndex: 'roleNames'
            }
        ];
        this.bbar = {
            xtype: 'paging',
            store: 'UserListStore',
            pageSize: 20,
            displayInfo: true
        };
        UserGridUi.superclass.initComponent.call(this);
    }
});


