/*
 * File: UserGrid.js
 * Date: Thu Apr 01 2010 02:27:47 GMT+0800 (?D1ú±ê×?ê±??)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.9.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

UserGrid = Ext.extend(UserGridUi, {
    initComponent: function() {
        UserGrid.superclass.initComponent.call(this);
        Ext.getCmp('user_add').on('click', this.onAdd, this);
        Ext.getCmp('user_edit').on('click', this.onEdit, this);
        Ext.getCmp('user_delete').on('click', this.onDelete, this);
    },
    onRender : function(){
    	UserGrid.superclass.onRender.apply(this, arguments);
    	this.store.load({params:{start:0,limit:20}});
    },
    onAdd : function(){
    	Ext.Msg.alert('adding...');
    },
	onEdit : function(){
    	Ext.Msg.alert('editing...');
    },
    onDelete : function(){
    	Ext.Msg.alert('deleting...');
    }
});
