/*
 * File: UserListStore.js
 * Date: Thu Apr 01 2010 05:14:55 GMT+0800 (?D1ú±ê×?ê±??)
 * 
 * This file was generated by Ext Designer version xds-1.0.0.9.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

UserListStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        UserListStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'UserListStore',
            root: 'data',
            idProperty: 'id',
            totalProperty: 'total',
            proxy: new Ext.data.HttpProxy({
			    api: {
				    read : 'security/user!list.action',
				    destroy: 'security/user!delete.action'
				}
			}),
            autoLoad: false,
            fields: [
                {
                    name: 'id',
                    mapping: 'id'
                },
                {
                    name: 'loginName',
                    mapping: 'loginName'
                },
                {
                    name: 'name',
                    mapping: 'name'
                },
                {
                    name: 'password',
                    mapping: 'password'
                },
                {
                    name: 'email',
                    mapping: 'email'
                },
                {
                    name: 'regionName',
                    mapping: 'regionName'
                },
                {
                    name: 'roleNames',
                    mapping: 'roleNames'
                }
            ]
        }, cfg));
    }
});
new UserListStore();